# https://nicolas-van.github.io/easy-markdown-to-github-pages/
theme: jekyll-theme-cayman
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - README_.md
  - content/robustness-efficiency-privacy.md
  - content/agi.md
  - content/cv-lab.md
  - content/dataset.md
  - content/over-domain-gap.md
  - content/image-restoration.md
  - content/visual-contents-creation.md
  - content/vision-transformer.md
  - content/deepfake-forensic.md
  - content/multi-modal-representation.md
  - content/physical-world.md
  - content/3d-representation.md